#!/bin/sh

# Setup a new configuration from a backup
# Incomplete
home_backup="~/backup/home/timo"

mkdir -p "$HOME/.local/share/task"
mkdir "$HOME/.config"

mv "$home_backup/.local/share/task/{*.data,*.pem}" "$HOME/.local/share/task/"
stow taskwarrior

mkdir "$HOME/data"
mv "$home_backup/data/*" "$HOME/data/"
