#! /bin/sh

bspc rule --add Firefox desktop='I' --one-shot; firefox >/dev/null &
bspc rule --add Telegram desktop='II' --one-shot; telegram >/dev/null &
bspc rule --add weechat desktop='II' --one-shot; termite -e 'weechat' &
