#! /bin/bash

bspc config border_width 2
bspc config window_gap 6
bspc config focused_border_color '#746c48'
bspc config focused_border_color '#FFFFFF'

bspc config split_ratio                0.5
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config history_aware_focus        true
bspc config focus_follows_pointer      true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true
bspc config single_monocle             true

# Configure my monitors
"$HOME/bin/monitor-configuration"
monitor_status=$? # 0 if monitors where changed, 2 otherwise
"$HOME/bin/wallpaper"

if [[ $monitor_status == 0 ]]; then
	if [[ "$(pgrep -cx bar_start)" -ge 1 ]] ; then
		echo "Restarting panel"
		pkill -x bar_start
	fi
fi

if [[ "$(pgrep -cx bar_start)" -eq 0 ]] ; then
	"$HOME/bin/bar/bar_start" & disown
fi

# Autostart only if no window is active yet
if [[ -z "$(xtitle)" ]]; then
	nohup "$HOME/.config/bspwm/autostart" > /dev/null & disown
fi
