#! /bin/sh
panel_dir="$HOME/.config/bspwm"

. "$panel_dir/panel_colors"

# monitor count
mon_count=$(bspc query -M | wc -l)

# read the input from stdin
while read -r line ; do
	case $line in
		S*)
			# date output
			date="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		D*)
			# due tasks
			due_nr=${line#?}
			if (( "$due_nr" == 0 )); then
				due=""
			else
				due="%{F$COLOR_DUE_FG}%{B$COLOR_DUE_BG} ${due_nr} tasks %{B-}%{F-}"
			fi
			;;
		A*)
			# updates
			updates_nr=${line#?}
			if (( "$updates_nr" == 0 )); then
				updates=""
			else
				updates="%{F$COLOR_UPDATES_FG}%{B$COLOR_UPDATES_BG} ${updates_nr} updates %{B-}%{F-}"
			fi
			;;
		P*)
			# power
			power=${line#?}
			power_status="%{F$COLOR_POWER_FG}%{B$COLOR_POWER_BG} ${power} %{B-}%{F-}"
			;;
		M*)
			# mail
			mail=${line#?}
			if [[ $mail -gt 0 ]]; then
				mail_status="%{F$COLOR_MAIL_FG}%{B$COLOR_MAIL_BG} ${mail} new %{B-}%{F-}"
			else
				mail_status=""
			fi
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			# set the positional parameters
			set -- ${line#?}
			# iterate over the positional parameters
			num=2
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ "$mon_count" -gt 1 ] ; then
			    			(( num-=1 ))
			    			wm_infos="$wm_infos %{S$num}"
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ "$mon_count" -gt 1 ] ; then
			    			(( num-=1 ))
			    			wm_infos="$wm_infos %{S$num}"
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
						;;
					L*)
						# layout
						wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm_infos}%{S1}%{c}${title}%{r}${due}${updates}${mail_status}${power_status}${date}"
done
