#! /bin/sh

if [ "$(pgrep -cx panel)" -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

# handle interrupts
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# (re-)create the named pipe
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# leave place in the WM for the bar
bspc config top_padding "$PANEL_HEIGHT"

# WM-info (workspaces, mode)
bspc control --subscribe > "$PANEL_FIFO" &

# active window
xtitle -sf 'T%s' > "$PANEL_FIFO" &

# date and time (for example Mon 14-12-30 13:45:10)
(while :; do date '+S%a %y-%m-%d %_H:%M:%S'; sleep 1s; done) > "$PANEL_FIFO" &

# use the colors specified in panel_colors
. "$(dirname "$0")/panel_colors"

# pipe the FIFO through panel_bar to format it and finally into
# the bar to display it
cat "$PANEL_FIFO" | "$(dirname "$0")/panel_bar" | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" | sh &

# keep the bar up to date, don't exit
wait
